SN/urls.py
from django.urls import path, re_path
from SN import views

urlpatterns = [
    path('', views.User_View, name='user_v'),
    path('regestration/', views.reg, name='rage'),
    path('dialogs/', views.Dialog_view, name='D_v'),
    re_path(r'^dialog/(?P<dialog_id>\w+)/$', views.Dialog, name='dialog_2'),
    path('Auth/', views.Auth, name='Auth')
]

SociaNet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SN.urls')),
]

SN/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class User_M(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='User_p')
    adress = models.TextField(max_length=128, blank=True, default='')
    phone = models.CharField(max_length=13, blank=True, default='')
    AboutMe = models.TextField(max_length=256, blank=True, default='')
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class User_photo(models.Model):
    user = models.ForeignKey(User_M, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='images/')
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


class Chat(models.Model):
    members = models.ManyToManyField(User)


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='A')
    message = models.TextField(max_length=256)

    def __str__(self):
        return self.message

SN/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .form import *


# Create your views here.
@login_required(login_url='Auth/')
def User_View(request):
    name = auth.get_user(request).username
    if request.method == 'POST':
        auth.logout(request)
    return render(request, 'User.html', locals())


def Mesage1(request):
    user = auth.get_user(request)
    Mesagelist = Message.objects.filter(sen=user)

    return render(request, 'Mesage.html', locals())


def reg(request):
    form = UserCreationForm()
    if request.method == 'POST':
        new_form = UserCreationForm(request.POST)
        if new_form.is_valid():
            new_form.save()
            aut = auth.authenticate(username=new_form.cleaned_data['username'],
                                    password=new_form.cleaned_data['password2'])
            auth.login(request, aut)
            return redirect('/')
    return render(request, 'Reg.html', locals())


def Auth(request):
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
    return render(request, 'Auth.html', locals())


def Dialog_view(request):
    chats = Chat.objects.filter(members__in=[request.user.id])
    user_id = request.user.id
    return render(request, 'Dialog.html', locals())


def Dialog(request, dialog_id):
    user = auth.get_user(request)
    chat = Chat.objects.get(id=dialog_id)
    msg = Message.objects.filter(chat=dialog_id)
    form = MessageForm(request.POST)
    if request.method == 'POST' and form.is_valid():
        message = form.save(commit=False)
        message.chat_id = dialog_id
        message.autor = request.user
        message.save()
        return redirect(request.path)

    return render(request, 'Mesage.html', locals())

templates/Auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div style="padding-top: 20%" class="text-center">
<form action="" method="post">
{% csrf_token %}
   <h1><label class="text-primary">Вход</label> <br></h1><br>
<label for="username">Name</label>
<input type="text" name="username" id="username">
<label for="password">Password</label>
<input type="password"  name="password" id="password"><br><br>
    <BUTTON class="btn bth-block btn-success " type="submit">Потвердить</BUTTON>

</form>
</div>
</body>
</html>

templates/Dialog.html
{% extends 'Obg.html' %}
{% block user %}
    {{ request.user }}
{% endblock %}
{% block content %}


<div class="row">

{% for chat in chats %}
    <div class="col-md-4 ">
    <a href="{% url 'dialog_2' chat.id %}">
        <div class="card bg-light mb-3" style="max-width: 18rem;">
  <div class="card-header">
  {% for member in chat.members.all %}
{% if member.id != user_id %}
    {{ member }}
      {% endif %}
      {% endfor %}
  </div>
  <div class="card-body">

    <p class="card-text">
      {{ chat.message_set.last }}
    </p>
  </div>

</div>
    </a>
</div>

    {% endfor %}
    </div>
{% endblock %}

templates/Mesage.html
{% extends 'Obg.html' %}

{%  block content %}
    <style>
    textarea{width: 100%;height: 100px}
    </style>
{% for message in msg  %}
   <div class="row">
   {% if message.autor != user %}
               <div class="col-md-6 text-left">
        <div class="alert alert-info">
            <h6>{{ message.autor }}</h6>
            {{ message.message }}
        </div>

        </div>

          <div class="col-md-6"></div>


   {% endif %}
   {% if message.autor == user %}
       <div class="col-md-6"></div>
        <div class="col-md-6 text-right">
        <div class="alert alert-info">
            <h6>{{ message.autor }}</h6>
            {{ message.message }}
        </div>

        </div>
   {% endif %}
   </div>
{% endfor %}

    <form action="" method="post">
    {% csrf_token %}

{{ form.message}}
    <button type='' class="btn-success">Send</button>
    </form>

{% endblock %}

templates/Obg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<style>

</style>
</head>
<body>
<header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark navbar-fixed-bottom bg-dark">
        <a class="navbar-brand" href="#">Fixed navbar</a>

       {% block user %}
          {% endblock %}
      </nav>
    </header>
<main>
<div class="container">

</div>
<div class="row">
<div class="col-md-2" >
<a href="{% url 'D_v' %}">Собщения</a>
</div>
<div class="col-md-10 text-center" >
{% block content %}
    {% endblock %}

</div>
</div>
</div>


</main>
</body>
</html>

templates/Reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>


<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">

        <div class="jumbotron p-4 p-md-5 text-white rounded bg-dark" style="margin-top: 10% ;align-content: center">
      <h1 class="display-4 font-italic" style=";">Регестрация</h1>
        <form method="post">
   {% csrf_token %}
{{ form.as_p }}
<button class="btn btn-success "  type="submit" >good</button>
</form>
  </div>

    </div>
    <div class="col-lg-2"></div>
</div>




</body>
</html>

templates/User.html
{% extends 'Obg.html' %}
{% block content %}
{% endblock %}